#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : watchdog
Version  : 2.1.6
Release  : 3
URL      : https://files.pythonhosted.org/packages/e8/a8/fc4edd7d768361b00ea850e5310211d157df6b5a1db6148dd434e787d898/watchdog-2.1.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/e8/a8/fc4edd7d768361b00ea850e5310211d157df6b5a1db6148dd434e787d898/watchdog-2.1.6.tar.gz
Summary  : Filesystem events monitoring
Group    : Development/Tools
License  : Apache-2.0
Requires: watchdog-bin = %{version}-%{release}
Requires: watchdog-license = %{version}-%{release}
Requires: watchdog-python = %{version}-%{release}
Requires: watchdog-python3 = %{version}-%{release}
Requires: PyYAML
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3

%description
Watchdog
========
|Build Status|
|CirrusCI Status|
Python API and shell utilities to monitor file system events.

%package bin
Summary: bin components for the watchdog package.
Group: Binaries
Requires: watchdog-license = %{version}-%{release}

%description bin
bin components for the watchdog package.


%package license
Summary: license components for the watchdog package.
Group: Default

%description license
license components for the watchdog package.


%package python
Summary: python components for the watchdog package.
Group: Default
Requires: watchdog-python3 = %{version}-%{release}

%description python
python components for the watchdog package.


%package python3
Summary: python3 components for the watchdog package.
Group: Default
Requires: python3-core
Provides: pypi(watchdog)

%description python3
python3 components for the watchdog package.


%prep
%setup -q -n watchdog-2.1.6
cd %{_builddir}/watchdog-2.1.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635537599
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/watchdog
cp %{_builddir}/watchdog-2.1.6/COPYING %{buildroot}/usr/share/package-licenses/watchdog/aa949e9aeb3398f2f58b1f03baba6c0b2173a476
cp %{_builddir}/watchdog-2.1.6/LICENSE %{buildroot}/usr/share/package-licenses/watchdog/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/watchmedo

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/watchdog/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/watchdog/aa949e9aeb3398f2f58b1f03baba6c0b2173a476

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
